// Original Paper E-style extension questions. These reproduce no ICAS items.
export const questionBank={
solar:[
 {stimulus:'Sydney receives about 14 h 25 min daylight in late December and 9 h 55 min in late June.',q:'Which model best explains this difference?',options:['Earth’s axis is tilted as Earth orbits the Sun','The Sun becomes cooler in June','Earth rotates more slowly in December'],answer:0,why:'Axial tilt changes both sunlight angle and day length; daily rotation remains about 24 hours.'},
 {stimulus:'At noon, a 1.0 m pole casts a 0.45 m shadow in summer and a 1.35 m shadow in winter.',q:'What conclusion is supported?',options:['The winter Sun is lower in the sky','The pole grows in summer','Summer sunlight travels more slowly'],answer:0,why:'For the same pole, a longer shadow indicates a lower solar elevation angle.'}],
rocks:[
 {stimulus:'Layer A: rounded coarse pebbles. Layer B: fine mud with leaf fossils. Layer C: cross-bedded sand.',q:'Which environment most likely formed Layer A?',options:['Fast-moving water','A still deep lake','Open air with no transport'],answer:0,why:'Fast water can carry coarse particles; rounding indicates collision during transport.'},
 {stimulus:'A rock contains interlocking crystals and no visible layers. It lies beside cooled lava.',q:'Which classification has the strongest evidence?',options:['Igneous','Sedimentary','Unconsolidated sediment'],answer:0,why:'Cooling molten material forms interlocking crystals; nearby lava supports this interpretation.'}],
space:[
 {stimulus:'A model uses 1 cm for 20,000 km. Planet X has a real diameter of 120,000 km.',q:'What diameter should Planet X have in the model?',options:['6 cm','24 cm','2.4 cm'],answer:0,why:'120,000 ÷ 20,000 = 6 cm.'},
 {stimulus:'Model A shows planet diameters to scale but compresses distances. Model B shows distances to scale but uses dots for planets.',q:'Which model should be used to compare orbital gaps?',options:['Model A','Model B','Neither model can represent a distance'],answer:1,why:'Model B preserves the quantity being compared: distance.'}],
'maps-rockets':[
 {stimulus:'Mean rocket heights: 100 mL → 14 m; 200 mL → 22 m; 300 mL → 19 m. Each mean uses four launches.',q:'What is the most defensible conclusion?',options:['200 mL gave the greatest mean height tested','Exactly 200 mL is always optimal','More water always increases height'],answer:0,why:'The evidence supports only tested volumes and shows the 300 mL mean fell.'},
 {stimulus:'A contour map has lines every 20 m. A path crosses 100, 120, 140, 160 and 180 m contours.',q:'What minimum vertical rise does the path show?',options:['80 m','100 m','20 m'],answer:0,why:'The elevation changes from 100 m to 180 m, a rise of 80 m.'}],
tectonics:[
 {stimulus:'Earthquakes beside a trench are shallow. Farther inland they become progressively deeper.',q:'Which structure best fits the evidence?',options:['A plate descends beneath another','A vertical crack reaches Earth’s centre','Two plates move apart symmetrically'],answer:0,why:'An inclined zone of increasing earthquake depth is evidence for subduction.'},
 {stimulus:'Seafloor ages are 2, 14 and 31 million years at 50, 350 and 750 km from a ridge.',q:'What approximate spreading trend is shown?',options:['Age increases with distance','Age decreases with distance','Age is unrelated to distance'],answer:0,why:'Every larger distance in the data has an older age.'}],
particles:[
 {stimulus:'A sealed syringe contains air. Its outlet is blocked and the plunger is pushed inward.',q:'Which particle explanation is best?',options:['Particles become smaller','Particles move closer while their size stays the same','Particles disappear through the walls'],answer:1,why:'Gas has large spaces between particles; compression reduces those spaces.'},
 {stimulus:'100 g of ice melts in a sealed container. The balance reads 100 g afterward.',q:'What principle does this demonstrate?',options:['Matter is conserved in a physical change','Ice has no particles','Liquids have no mass'],answer:0,why:'The particles rearrange and move differently, but none are created or destroyed.'}],
mixtures:[
 {stimulus:'A mixture contains iron filings, salt and sand. Available tools: magnet, water, filter and evaporating dish.',q:'Which sequence separates all three?',options:['Magnet; add water; filter; evaporate','Filter; magnet; freeze','Evaporate; add water; magnet'],answer:0,why:'Remove iron magnetically, dissolve salt, filter sand, then recover salt by evaporation.'},
 {stimulus:'A dye travels 6.0 cm while the solvent front travels 8.0 cm.',q:'What is the dye’s relative travel ratio?',options:['0.75','1.33','2.0'],answer:0,why:'Relative travel = dye distance ÷ solvent distance = 6.0 ÷ 8.0 = 0.75.'}],
changes:[
 {stimulus:'Two clear liquids mix. Temperature falls from 22°C to 12°C and a white solid appears.',q:'Which observation is strongest evidence of new substances?',options:['A precipitate forms','Both liquids began clear','The beaker remains the same size'],answer:0,why:'An insoluble solid forming from two solutions is strong evidence of a chemical reaction.'},
 {stimulus:'Candle wax melts near the flame while wax vapour burns above the wick.',q:'How should the two changes be classified?',options:['Both physical','Melting physical; burning chemical','Melting chemical; burning physical'],answer:1,why:'Melting changes state; combustion produces new substances.'}],
'structures-lab':[
 {stimulus:'Cylinder marks are every 2 mL. The meniscus lies halfway between 36 mL and 38 mL.',q:'What reading should be recorded?',options:['37 mL','36 mL','38.5 mL'],answer:0,why:'Halfway between the marked values is 37 mL.'},
 {stimulus:'Five repeated masses are 12.41, 12.40, 12.42, 12.41 and 12.40 g, but a certified mass is 12.90 g.',q:'The measurements are…',options:['Precise but inaccurate','Accurate but imprecise','Both accurate and precise'],answer:0,why:'They agree closely with one another but are far from the accepted value.'}],
'chem-environment':[
 {stimulus:'Downstream of a farm, nitrate rises from 0.4 to 6.8 mg/L and dissolved oxygen falls from 8.1 to 3.2 mg/L.',q:'Which additional comparison would best test whether the farm is the source?',options:['Repeated upstream and downstream samples','One downstream photograph','The colour of the sample bottle'],answer:0,why:'Repeated paired sites establish whether the spatial pattern persists and reduce chance variation.'},
 {stimulus:'Yeast dough gains gas bubbles and ethanol while sugar concentration falls.',q:'What supports a chemical interpretation?',options:['New substances form as sugar is consumed','The dough changes shape only','The bowl is round'],answer:0,why:'Consumption of a reactant and production of gas and ethanol indicate chemical change.'}],
cells:[
 {stimulus:'Cell X has many mitochondria and a long tail. Cell Y has a large surface extension and no chloroplasts.',q:'Which pairing is most plausible?',options:['X sperm; Y root-hair cell','X red blood cell; Y leaf cell','X guard cell; Y muscle fibre'],answer:0,why:'A sperm needs energy and propulsion; a root-hair extension increases absorption area.'},
 {stimulus:'A cell is placed in concentrated salt solution and its membrane pulls away from the cell wall.',q:'What movement best explains this?',options:['Water leaves the cell','Salt turns into water','The cell wall dissolves'],answer:0,why:'Water moves out across the membrane, reducing the cell contents’ volume.'}],
ecosystems:[
 {stimulus:'Grass → rabbit → fox. Grass → grasshopper → lizard → fox.',q:'If lizards sharply decline, what is the most direct expected effect?',options:['Grasshoppers increase','Rabbits immediately disappear','Grass gains energy from foxes'],answer:0,why:'Reduced predation on grasshoppers is the closest direct link.'},
 {stimulus:'Producers store 18,000 kJ; primary consumers 2,100 kJ; secondary consumers 240 kJ.',q:'Why does available energy decline?',options:['Energy is transferred to surroundings and used in life processes','Matter and energy vanish identically','Consumers create cold'],answer:0,why:'Respiration and other processes transfer much energy as heat; not all biomass is eaten or assimilated.'}],
body:[
 {stimulus:'During exercise: heart rate 72→148 bpm; breathing 14→32/min; blood oxygen stays near 97%.',q:'Why can blood oxygen remain fairly stable?',options:['Ventilation and circulation increase delivery','Muscles stop respiring','Oxygen is not used during exercise'],answer:0,why:'Coordinated responses supply oxygen fast enough to maintain saturation in a healthy person.'},
 {stimulus:'Alveoli are numerous, thin-walled, moist and surrounded by capillaries.',q:'Which two features most directly shorten diffusion distance and maintain a gradient?',options:['Thin walls and blood flow','Large lungs and ribs','Moisture and body height'],answer:0,why:'Thin walls shorten the path; flowing blood removes oxygen and brings carbon dioxide.'}],
classification:[
 {stimulus:'1a six legs→2; 1b eight legs→spider. 2a one wing pair→fly; 2b two wing pairs→3. Specimen: six legs, two wing pairs.',q:'What should the user do next?',options:['Go to step 3','Identify it as a spider','Identify it as a fly'],answer:0,why:'The specimen follows 1a and then 2b.'},
 {stimulus:'Animal P dental formula has large canines and blade-like premolars. Animal Q has no upper incisors and broad ridged molars.',q:'Which inference is strongest?',options:['P is adapted for tearing; Q for grinding','Both eat exactly the same food','Q must hunt P'],answer:0,why:'Tooth shapes support feeding adaptations, although they do not prove a complete diet.'}],
'bio-investigation':[
 {stimulus:'Plant means at 10, 20, 30°C are 4.2, 8.7, 6.1 cm. Sample sizes are 2, 30 and 3.',q:'Why should the apparent optimum be treated cautiously?',options:['Sample sizes are unequal and two are very small','Means can never be compared','Temperature has no units'],answer:0,why:'Small, unequal samples give different reliability and may exaggerate chance differences.'},
 {stimulus:'A scatter plot shows more fertiliser is associated with taller plants, but high-fertiliser pots also received more light.',q:'What is the main design problem?',options:['Light is a confounding variable','Height is categorical','Fertiliser cannot be measured'],answer:0,why:'Because light changed with fertiliser, either variable could explain the height pattern.'}],
forces:[
 {stimulus:'A 6 kg trolley has a net horizontal force of 18 N.',q:'Using F = ma, what is its acceleration?',options:['3 m/s²','108 m/s²','0.33 m/s²'],answer:0,why:'a = F ÷ m = 18 ÷ 6 = 3 m/s².'},
 {stimulus:'A skydiver falls at constant velocity.',q:'What must be true of the vertical forces?',options:['Air resistance equals weight','Weight is zero','Air resistance is greater than weight'],answer:0,why:'Constant velocity means zero acceleration and therefore zero net force.'}],
circuits:[
 {stimulus:'Two identical lamps are in series. A third identical lamp is added in series.',q:'What usually happens?',options:['Current falls and lamps become dimmer','Current rises without limit','Only the battery becomes a conductor'],answer:0,why:'Adding series resistance reduces current for the same supply voltage.'},
 {stimulus:'An ammeter is connected directly across a battery instead of in series with a lamp.',q:'Why is this unsafe or invalid?',options:['Its low resistance can produce a very large current','It measures light','It makes voltage disappear permanently'],answer:0,why:'Ammeters have very low resistance and must not form a near-short circuit across a source.'}],
energy:[
 {stimulus:'A motor receives 500 J and transfers 325 J usefully to motion.',q:'What percentage is usefully transferred?',options:['65%','35%','175%'],answer:0,why:'Efficiency = 325 ÷ 500 × 100 = 65%.'},
 {stimulus:'A Sankey diagram has a 40-unit input arrow, 12-unit wasted branch and one useful output.',q:'How large is the useful output?',options:['28 units','52 units','3.3 units'],answer:0,why:'Conservation requires 40 = 12 + useful, so useful = 28.'}],
'light-sound':[
 {stimulus:'Sound A: 250 Hz, amplitude 2 units. Sound B: 500 Hz, amplitude 2 units.',q:'How does B compare with A?',options:['Higher pitch, similar amplitude','Louder, lower pitch','Same pitch, double amplitude'],answer:0,why:'B has twice the frequency, so has higher pitch; listed amplitudes are equal.'},
 {stimulus:'A ray enters glass from air and bends towards the normal.',q:'Which explanation fits?',options:['Light travels more slowly in glass','The normal pushes the light','Light gains mass at the boundary'],answer:0,why:'A speed decrease is associated with bending towards the normal.'}],
'motion-electricity':[
 {stimulus:'A student travels 120 m in 30 s, rests 20 s, then travels 180 m in 50 s.',q:'What is the average speed for the whole interval?',options:['3.0 m/s','4.0 m/s','6.0 m/s'],answer:0,why:'Total distance is 300 m and total time, including rest, is 100 s: 3.0 m/s.'},
 {stimulus:'A distance–time graph rises straight from (0 s, 0 m) to (8 s, 24 m), then is horizontal until 12 s.',q:'Which description is correct?',options:['3 m/s for 8 s, then stationary','24 m/s for 8 s, then accelerating','3 m/s for 12 s continuously'],answer:0,why:'The first gradient is 24÷8 = 3 m/s; horizontal distance means no movement.'}],
'water-cycle':[
 {stimulus:'A region records average monthly rainfall over 30 years to describe its typical wet and dry seasons.',q:'This 30-year rainfall record is best described as data about…',options:['Climate','A single weather event','Tomorrow’s forecast only'],answer:0,why:'Long-term averages over many years describe climate, not one day’s weather.'},
 {stimulus:'On a weather map, isobars near city P are close together while isobars near city Q are widely spaced.',q:'Which conclusion is best supported?',options:['City P likely experiences stronger winds than city Q','City P is warmer than city Q','City Q will definitely rain'],answer:0,why:'Closely spaced isobars indicate a steeper pressure gradient, generally associated with stronger winds.'}],
reactions:[
 {stimulus:'Metal J displaces metal K from solution. Metal K displaces metal L from solution. Metal L cannot displace metal J.',q:'Which order lists the metals from most to least reactive?',options:['J, K, L','L, K, J','K, J, L'],answer:0,why:'A metal that displaces another is more reactive, giving the order J > K > L.'},
 {stimulus:'A student burns 4.0 g of a candle in an open dish. After burning, the dish and remaining wax have a lower total mass than before.',q:'What best explains the apparent mass loss?',options:['Gaseous products escaped into the air rather than mass truly vanishing','Mass was destroyed during burning','The balance became less accurate as wax burned'],answer:0,why:'Combustion produces gases such as carbon dioxide and water vapour that leave the open system, so measured mass on the dish falls even though total mass is conserved.'}],
'body-systems':[
 {stimulus:'A student steps on a sharp object and immediately lifts their foot before consciously feeling pain.',q:'Which pathway best explains the rapid foot lift?',options:['A reflex arc through the nervous system','Direct action by the digestive system','The skeletal system acting without any signal'],answer:0,why:'A reflex arc processes signals through the spinal cord for a rapid response, faster than conscious brain processing.'},
 {stimulus:'Diagram: mouth → oesophagus → stomach → small intestine → large intestine.',q:'Which organ mainly absorbs digested nutrients into the blood?',options:['Small intestine','Oesophagus','Mouth'],answer:0,why:'The small intestine has a large folded surface area specialised for nutrient absorption.'}],
renewables:[
 {stimulus:'A remote island currently relies on diesel generators shipped in by boat. Engineers propose adding solar panels with battery storage.',q:'Which is a genuine advantage of adding solar panels with storage in this situation?',options:['Reduced dependence on shipped fuel and lower running emissions','Guaranteed identical output every single day','No equipment ever needs maintenance'],answer:0,why:'Solar power reduces reliance on transported fuel and cuts emissions during generation, though output still varies with weather.'},
 {stimulus:'Table: Coal — high reliability, high emissions, low direct fuel-cost variability. Wind — low emissions, variable output, no fuel cost.',q:'Which statement uses only the table’s information?',options:['Coal is more reliable but produces more emissions than wind in this table','Wind is reliable at all times','Coal produces no emissions'],answer:0,why:'The table directly states coal is high reliability/high emissions and wind is variable/low emissions.'}]
};

// A fourth question per mission targets recurring public Paper E item patterns:
// indirect measurement, keys, constraint diagrams, fair tests and limits of data.
const predicted={
 solar:{prediction:'HIGH',focus:'diagram inference',stimulus:'Four identical solar panels are tilted at 10°, 25°, 40° and 55°. At noon their outputs are 68, 83, 91 and 79 W.',q:'Which claim goes beyond the evidence?',options:['40° gave the greatest output tested','Panel angle affected output','40° is the best angle at every place and time','55° produced 11 W more than 10°'],answer:2,why:'The investigation supports this time, place and tested range. It cannot establish a universal best angle.'},
 rocks:{prediction:'MEDIUM',focus:'table and sequence reasoning',stimulus:'A sequence contains, from bottom to top: sandstone, a thin ash layer, shale and conglomerate. The ash is dated at 82 million years.',q:'Which statement is best supported?',options:['The sandstone is older than 82 million years','The conglomerate is exactly 82 million years old','All layers formed at the same time','Shale is always volcanic'],answer:0,why:'In an undisturbed sequence lower layers predate upper layers; the sandstone lies below the dated ash.'},
 space:{prediction:'HIGH',focus:'indirect ratio measurement',stimulus:'In an image, a 3.0 m probe spans 12 mm and an asteroid spans 70 mm.',q:'What is the best estimate of the asteroid width?',options:['17.5 m','5.8 m','210 m','28 m'],answer:0,why:'The image ratio is 70÷12, so real width is 3.0×70÷12 = 17.5 m.'},
 'maps-rockets':{prediction:'HIGH',focus:'fair test critique',stimulus:'Rocket W: 100 mL water, 300 kPa, fins A. Rocket X: 200 mL, 300 kPa, fins A. Rocket Y: 300 mL, 450 kPa, fins B.',q:'Which comparison fairly tests water volume?',options:['W with X','X with Y','W with Y','All three equally'],answer:0,why:'Only W and X differ in water volume; pressure and fin type remain controlled.'},
 tectonics:{prediction:'HIGH',focus:'combined evidence',stimulus:'Boundary P has shallow earthquakes and a central ridge. Boundary Q has a trench, volcanoes and earthquakes that deepen inland.',q:'Which identification fits both datasets?',options:['P divergent; Q convergent','P convergent; Q divergent','Both transform','Both inactive'],answer:0,why:'Ridges and shallow quakes fit spreading; a trench and dipping quake zone fit subduction.'},
 particles:{prediction:'HIGH',focus:'model transfer',stimulus:'A sealed steel can containing air is heated. Its volume changes negligibly.',q:'Which change produces the increased pressure?',options:['Particles move faster and collide harder and more often','Each particle expands greatly','New air particles appear','The spaces fill with heat particles'],answer:0,why:'Heating increases average kinetic energy; in fixed volume, wall collisions become more frequent and forceful.'},
 mixtures:{prediction:'MEDIUM',focus:'multi-step procedure',stimulus:'Powder contains soluble blue crystals, insoluble chalk and magnetic iron.',q:'After using a magnet and then stirring with water, what should happen next to recover chalk?',options:['Filter the mixture','Evaporate before filtering','Use another magnet only','Distil the dry powder'],answer:0,why:'Chalk remains an insoluble solid and is retained by filter paper while the blue solution passes through.'},
 changes:{prediction:'HIGH',focus:'alternative explanation',stimulus:'A tablet placed in water produces bubbles and the beaker becomes colder.',q:'What extra observation most strongly shows the bubbles come from a new gas rather than boiling?',options:['The water is below its boiling point and products differ from reactants','The tablet is round','The beaker is transparent','The bubbles move upward'],answer:0,why:'Temperature rules out boiling, while changed products provide chemical evidence.'},
 'structures-lab':{prediction:'HIGH',focus:'constraint diagram',stimulus:'Strings W, X and Y break above 8 N, 15 N and 24 N. A hanging load pulls on all three in one vertical chain.',q:'What is the greatest load the chain can safely support?',options:['8 N','15 N','24 N','47 N'],answer:0,why:'Every string carries the load, so the weakest string sets the chain limit.'},
 'chem-environment':{prediction:'HIGH',focus:'limits of tabulated evidence',stimulus:'A table marks whether four sites contain nitrate, sediment and pathogens. It gives no concentrations.',q:'Which question cannot be answered from this table?',options:['Which pollutant types were detected?','Which site had the greatest mass of nitrate?','Did any site contain pathogens?','How many sites contained sediment?'],answer:1,why:'Presence/absence data do not show concentration or total mass.'},
 cells:{prediction:'HIGH',focus:'microscope magnification',stimulus:'A cell image is 48 mm long at ×400 magnification.',q:'What is the cell’s real length?',options:['0.12 mm','1.2 mm','19.2 mm','192 mm'],answer:0,why:'Real size = image size ÷ magnification = 48÷400 = 0.12 mm.'},
 ecosystems:{prediction:'HIGH',focus:'indirect food-web effect',stimulus:'Seeds feed mice and parrots. Mice feed snakes. A disease sharply reduces mice.',q:'Which paired outcome is plausible?',options:['More seeds and fewer snakes','Fewer seeds and more snakes','Fewer parrots because snakes eat seeds','No population can change'],answer:0,why:'Fewer mice consume fewer seeds and provide less prey for snakes; indirect effects may also occur.'},
 body:{prediction:'MEDIUM',focus:'rate calculation',stimulus:'A student counts 19 beats in 15 seconds immediately after exercise.',q:'What is the estimated heart rate?',options:['76 bpm','34 bpm','285 bpm','19 bpm'],answer:0,why:'Fifteen seconds is one quarter of a minute, so 19×4 = 76 beats per minute.'},
 classification:{prediction:'HIGH',focus:'branching key',stimulus:'1a wings present→2; 1b absent→4. 2a one wing pair→fly; 2b two pairs→3. 3a narrow waist→wasp; 3b no narrow waist→termite. Specimen has four wings and a narrow waist.',q:'Where does the key lead?',options:['Wasp','Fly','Termite','Step 4'],answer:0,why:'Wings lead to 2, two pairs lead to 3, and a narrow waist identifies wasp.'},
 'bio-investigation':{prediction:'HIGH',focus:'fair-test diagnosis',stimulus:'Detergents W, X, Y and Z are tested on different fabrics, at different temperatures, for the same wash time.',q:'Why can cleaning differences not be attributed confidently to detergent?',options:['Fabric and temperature are confounding variables','Wash time was controlled','Four detergents are too many in principle','Cleaning cannot be measured'],answer:0,why:'Several explanatory variables changed together, so the detergent effect cannot be isolated.'},
 forces:{prediction:'HIGH',focus:'linked constraints',stimulus:'A 20 N sign hangs from two identical vertical cables, each rated to 12 N. The load is shared equally.',q:'What conclusion follows?',options:['Each carries 10 N, so neither exceeds its rating','Each carries 20 N and breaks','Ratings add to 144 N','Cable force is zero'],answer:0,why:'For equal vertical sharing, each tension is half the 20 N weight: 10 N.'},
 circuits:{prediction:'HIGH',focus:'meter diagram reasoning',stimulus:'A student wants current through a lamp and voltage across it.',q:'Which arrangement is correct?',options:['Ammeter in series; voltmeter parallel to lamp','Both meters in series','Ammeter parallel; voltmeter series','Both directly across the battery only'],answer:0,why:'Current passes through an ammeter; a voltmeter compares potential at the lamp’s two terminals.'},
 energy:{prediction:'MEDIUM',focus:'Sankey proportional reasoning',stimulus:'A device is 72% efficient and receives 250 J.',q:'How much energy is dissipated?',options:['70 J','180 J','178 J','322 J'],answer:0,why:'Useful energy is 0.72×250 = 180 J, leaving 250−180 = 70 J dissipated.'},
 'light-sound':{prediction:'HIGH',focus:'ray diagram geometry',stimulus:'A ray makes an angle of 32° with a flat mirror surface.',q:'What angle does the reflected ray make with the normal?',options:['58°','32°','64°','148°'],answer:0,why:'The incident angle to the normal is 90−32 = 58°, equal to the reflection angle.'},
 'motion-electricity':{prediction:'HIGH',focus:'multi-stage calculation',stimulus:'A runner covers 150 m in 25 s, then 250 m in 35 s.',q:'What average speed applies to the entire trip?',options:['6.67 m/s','6.00 m/s','7.14 m/s','13.14 m/s'],answer:0,why:'Average speed uses totals: 400 m ÷ 60 s = 6.67 m/s.'},
 'water-cycle':{prediction:'MEDIUM',focus:'cycle stage reasoning',stimulus:'A sealed, clear container holds damp soil and a plant. After several sunny days, droplets appear on the inside of the lid.',q:'Which process most directly explains the droplets?',options:['Water evaporated from the soil and plant, then condensed on the cooler lid','The plant produced new water inside its leaves','The container manufactured water vapour'],answer:0,why:'Warmed water vapour rises and condenses on the cooler surface, mirroring the water cycle in miniature.'},
 reactions:{prediction:'HIGH',focus:'mass-balance calculation',stimulus:'12 g of a carbonate reacts completely with acid in a sealed flask, releasing carbon dioxide gas that stays trapped inside. The flask and contents have the same total mass before and after.',q:'If the flask were opened immediately after the reaction, what would most likely happen to its measured mass?',options:['It would decrease as trapped carbon dioxide escapes','It would increase as new gas enters','It would stay exactly the same forever','Mass cannot change once measured'],answer:0,why:'Opening the flask lets the gaseous product escape, reducing the mass measured on a balance even though no matter was destroyed.'},
 'body-systems':{prediction:'MEDIUM',focus:'reaction-time data',stimulus:'Mean ruler-drop reaction distances: no distraction 9 cm; while counting backwards 15 cm; five trials each.',q:'What is the best-supported conclusion?',options:['Reaction distance was greater under the distraction condition tested','Distraction always doubles reaction time in everyone','Counting backwards improves reflexes'],answer:0,why:'The evidence supports only the tested comparison; broader claims about everyone go beyond the data.'},
 renewables:{prediction:'HIGH',focus:'trade-off evaluation',stimulus:'A report claims: "Hydroelectric power should replace all other sources because it produces electricity without burning fuel."',q:'Which response best evaluates this claim?',options:['The claim ignores trade-offs such as land and ecosystem impact from dams and site-dependent availability','The claim is completely correct with no exceptions','Hydroelectric power always produces more emissions than coal','Fuel-free means there are no other considerations'],answer:0,why:'A sound evaluation checks a claim against overlooked trade-offs rather than accepting a single advantage as decisive.'}
};
for(const [id,q] of Object.entries(predicted)) questionBank[id].push(q);

// New questions derived from structural patterns visible in the public preview
// of the 2016 Paper E upload. Scenarios, values and answers are original.
const archivePatterns={
 solar:{prediction:'MEDIUM',focus:'apparent sky motion',stimulus:'A camera points through a west-facing window. Stars P, Q and R appear near the western horizon, high in the centre and near the eastern horizon. Earth rotates west to east.',q:'Which star is expected to leave the west-facing view first?',options:['The star nearest the western horizon','The central star regardless of direction','All stars vanish simultaneously','The faintest star'],answer:0,why:'Earth’s rotation makes the sky appear to move east to west, so the object already nearest the western boundary exits first.'},
 rocks:{prediction:'MEDIUM',focus:'reactivity and preservation',stimulus:'Metal order, most to least reactive: M, N, iron, P, copper, Q. Identical objects are buried in moist soil for 500 years.',q:'Which object is most likely to remain least changed?',options:['Q','M','N','Iron'],answer:0,why:'The least reactive listed metal is least likely to combine with water, oxygen or soil chemicals.'},
 space:{prediction:'MEDIUM',focus:'scientific notation',stimulus:'A comet has a mass of 6 × 10¹⁴ kg. A fragment has one thousandth of this mass.',q:'How should the fragment’s mass be written?',options:['6 × 10¹¹ kg','6 × 10¹⁷ kg','0.6 × 10¹⁴ kg','6 × 10⁻¹⁴ kg'],answer:0,why:'One thousandth is 10⁻³, so 6×10¹⁴×10⁻³ = 6×10¹¹.'},
 'maps-rockets':{prediction:'HIGH',focus:'spatial source inference',stimulus:'A map shows 31 illness cases clustered within 250 m of pump B, 6 scattered near pump A and 3 near pump C. Population around each pump is similar.',q:'Which first investigation is best?',options:['Test water from pump B and compare with other pumps','Close every road','Assume pump B is guilty without sampling','Count only the houses without illness'],answer:0,why:'The cluster identifies a hypothesis; comparative water testing supplies evidence about the proposed source.'},
 tectonics:{prediction:'MEDIUM',focus:'timeline inference',stimulus:'Instrument P was invented in 1880. Discovery X occurred in 1860, Y in 1905 and Z in 1950.',q:'Which discovery could have used instrument P directly?',options:['Y and Z only','X only','X, Y and Z','None'],answer:0,why:'Only discoveries after the invention could have used the instrument.'},
 particles:{prediction:'HIGH',focus:'osmosis particle model',stimulus:'A membrane passes water but not sugar. Side A has 5 sugar particles per 100 water particles; side B has 20 per 100.',q:'What is the initial net water movement?',options:['A to B','B to A','Sugar moves B to A','No particles move'],answer:0,why:'Water moves from the more dilute side A towards the more concentrated side B through the membrane.'},
 mixtures:{prediction:'HIGH',focus:'process flowchart',stimulus:'Waste passes through: size screen removes large card; magnet removes iron; conductivity separator removes aluminium. A batch contains large card, iron screws, aluminium cans and glass.',q:'What remains after all three stages?',options:['Glass','Iron screws','Aluminium cans','Large card'],answer:0,why:'Each other material matches a stated removal stage; glass matches none.'},
 changes:{prediction:'MEDIUM',focus:'formula decoding',stimulus:'Compound J is A₂B. Compound K is AB₃. A model set contains 4 circles and 2 triangles.',q:'If circles represent A and triangles B, which complete molecules can be made without exceeding the set?',options:['Two J molecules','Two K molecules','Four J molecules','Three K molecules'],answer:0,why:'Two A₂B molecules use 4 A and 2 B. Two J molecules use all 4 A and both B shapes; K requires three B shapes per molecule.'},
 'structures-lab':{prediction:'HIGH',focus:'precision from graph design',stimulus:'Four sensors measure the accepted values 1, 2 and 3 units. Sensor A is consistently 0.5 high. Sensor B alternates ±0.8. Sensor C matches each accepted value. Each setting is measured only once.',q:'Which statement is valid?',options:['C appears most accurate, but precision cannot be determined','A is most accurate and precise','B is most accurate','C is proven most precise'],answer:0,why:'C is closest to accepted values. Precision requires repeated measurements at the same setting.'},
 'chem-environment':{prediction:'HIGH',focus:'reactivity-series deduction',stimulus:'Metal R displaces S from solution. T displaces R. S cannot displace R.',q:'Which order is consistent, most reactive first?',options:['T, R, S','S, R, T','R, T, S','T, S, R'],answer:0,why:'A metal that displaces another is more reactive: T > R > S.'},
 cells:{prediction:'HIGH',focus:'structure comparison only',stimulus:'Cell W has a wall, nucleus and chloroplasts. Cell X has a nucleus but no wall. Cell Y has a wall but no nucleus.',q:'Which conclusion uses only the observations?',options:['W and Y both have walls','W and X photosynthesise','Y is larger than W','X came from a predator'],answer:0,why:'The shared wall is directly recorded; the other statements require unsupported assumptions.'},
 ecosystems:{prediction:'MEDIUM',focus:'life-cycle survival strategy',stimulus:'An insect lays 900 eggs, spends years underground as a juvenile, then adults emerge together and many are eaten.',q:'Which feature most directly offsets heavy predation at emergence?',options:['Producing many offspring','Living underground proves adults cannot be eaten','Having six legs','Emerging makes predators disappear'],answer:0,why:'Large offspring number increases the chance that some survive and reproduce despite predation.'},
 body:{prediction:'HIGH',focus:'anatomy diagram comparison',stimulus:'Animal W has 18 body segments and one leg pair per segment. Animal X has 12 segments and two leg pairs per segment.',q:'Which statement follows from the data?',options:['Both have 24 legs','W has fewer legs than X','They eat the same food','W has twice as many segments'],answer:1,why:'W has 18 pairs and X has 24 pairs. Diet is not shown, and 18 is not twice 12.'},
 classification:{prediction:'HIGH',focus:'key plus new specimen',stimulus:'A key separates flowers by scent, colour and tube length. A new flower is red, scentless and has a 35 mm tube.',q:'What information must a valid key contain to identify it?',options:['Branches covering those observable features','The flower’s popularity','Its exact age only','A photograph with no labels'],answer:0,why:'A usable key must provide mutually exclusive branches for the specimen’s observed characteristics.'},
 'bio-investigation':{prediction:'HIGH',focus:'reliability improvement',stimulus:'One new battery of each brand is tested in the same torch until the light turns off.',q:'Which change best improves reliability?',options:['Test several batteries of each brand and compare means','Use a different torch for each brand','Add more brands but keep one trial each','Draw a colourful graph'],answer:0,why:'Replication estimates natural variation and reduces the effect of an unusual battery.'},
 forces:{prediction:'HIGH',focus:'speed graph interval',stimulus:'Velocity rises uniformly from 4 to 10 m/s over 3 s, remains 10 m/s for 5 s, then falls to 0 over 2 s.',q:'During which interval is acceleration zero?',options:['The 5 s at constant velocity','The first 3 s','The final 2 s','No interval'],answer:0,why:'Acceleration is change in velocity per time; velocity is unchanged during the middle interval.'},
 circuits:{prediction:'HIGH',focus:'multi-switch logic',stimulus:'Two lamps are on separate parallel branches. Switch P is in the main line; switch Q is only in lamp 2’s branch.',q:'What happens when P is closed and Q is open?',options:['Lamp 1 on; lamp 2 off','Both on','Both off','Lamp 1 off; lamp 2 on'],answer:0,why:'The main path is supplied, but Q breaks only lamp 2’s branch.'},
 energy:{prediction:'HIGH',focus:'machine efficiency',stimulus:'Machine W receives 800 J and gives 520 J useful output. Machine X receives 600 J and gives 420 J useful output.',q:'Which machine is more efficient?',options:['X at 70%','W at 80%','W at 65% is more efficient','They are equally efficient'],answer:0,why:'W is 520/800 = 65%; X is 420/600 = 70%, so X is more efficient.'},
 'light-sound':{prediction:'MEDIUM',focus:'dual-series graph reading',stimulus:'At 100, 200 and 400 Hz, material A absorbs 20%, 35%, 60%; material B absorbs 45%, 40%, 30%.',q:'At which listed frequency is the difference smallest?',options:['200 Hz','100 Hz','400 Hz','The difference is equal'],answer:0,why:'Differences are 25, 5 and 30 percentage points, so 200 Hz is smallest.'},
 'motion-electricity':{prediction:'HIGH',focus:'accuracy versus precision',stimulus:'At an accepted current of 1.00 A, meter W gives 1.20, 1.20, 1.20 A; meter X gives 0.98, 1.01, 1.00 A.',q:'Which assessment is correct?',options:['W is precise but inaccurate; X is accurate and reasonably precise','W is accurate because readings match','X is imprecise because values are not identical','Neither can measure current'],answer:0,why:'W repeats closely but is offset; X clusters closely around the accepted value.'},
 'water-cycle':{prediction:'MEDIUM',focus:'graph trend across seasons',stimulus:'Average monthly evaporation at a reservoir is 40 mm in June, 65 mm in September and 210 mm in January.',q:'What trend does the data show across these months?',options:['Evaporation increases from June to January','Evaporation decreases from June to January','Evaporation stays constant'],answer:0,why:'Each later listed month has a higher evaporation value than the one before it, consistent with rising temperatures approaching summer.'},
 reactions:{prediction:'MEDIUM',focus:'word equation completion',stimulus:'Iron reacts with sulfur when heated, forming a single new compound called iron sulfide.',q:'Which word equation correctly represents this reaction?',options:['Iron + sulfur → iron sulfide','Iron sulfide → iron + sulfur','Iron + iron sulfide → sulfur'],answer:0,why:'Reactants are written before the arrow and the single new product after it.'},
 'body-systems':{prediction:'MEDIUM',focus:'system interdependence',stimulus:'After a large meal, blood flow to the digestive system increases so more nutrients can be absorbed, while blood flow to some other regions is temporarily reduced.',q:'What does this best illustrate?',options:['Body systems share and prioritise limited resources such as blood flow','Digestion stops all other systems permanently','Only the digestive system needs blood'],answer:0,why:'Coordinated regulation of blood flow shows body systems interacting rather than working in isolation.'},
 renewables:{prediction:'MEDIUM',focus:'proportional reasoning with mixed sources',stimulus:'A region generates electricity from sources in this mix: coal 45%, gas 20%, wind 25%, solar 10%.',q:'What percentage of this region’s electricity comes from renewable sources listed?',options:['35%','45%','65%'],answer:0,why:'Wind and solar are the renewable sources listed: 25% + 10% = 35%.'}
};
for(const [id,q] of Object.entries(archivePatterns)) questionBank[id].push(q);

// A sixth question per mission is modelled on the officially published ICAS
// Science Assessment Framework's higher-tier Paper F/G example categories
// (e.g. changes-of-state graphs, random sampling, potential/kinetic energy,
// effects of current on the body) — the most current framework ICAS
// distributes, current 2019+ Paper E papers being paywalled and unavailable
// for direct reference. Scenarios, values and answers are original.
const latestPatterns={
 solar:{prediction:'MEDIUM',focus:'stellar brightness graph',stimulus:'A graph plots four stars’ brightness against surface temperature. Star P is hot and very bright; Star Q is cool and very dim; Star R is hot but dim; Star S is cool but very bright.',q:'Which two stars have the greatest difference in brightness for a similar temperature?',options:['Star P and Star R','Star P and Star Q','Star R and Star S'],answer:0,why:'P and R share a similar (hot) temperature but differ greatly in brightness, isolating brightness as the varying factor.'},
 rocks:{prediction:'MEDIUM',focus:'hardness-scale identification',stimulus:'A hardness table lists, softest to hardest: talc, gypsum, quartz, diamond. An unknown mineral scratches gypsum but is itself scratched by quartz.',q:'Where does the unknown mineral rank on this table?',options:['Between gypsum and quartz','Softer than talc','Harder than diamond'],answer:0,why:'It can scratch a softer mineral but is scratched by a harder one, placing it in between on the scale.'},
 space:{prediction:'MEDIUM',focus:'comparing models at different scales',stimulus:'Model X shows only the eight planets orbiting the Sun to scale. Model Y shows the Sun as one of billions of stars within the Milky Way galaxy.',q:'Which statement correctly compares the two models?',options:['Model X represents the solar system; Model Y represents the far larger scale of the galaxy','Both models represent exactly the same scale','Model Y cannot include the Sun'],answer:0,why:'Model X is limited to the solar system, while Model Y represents the much larger galactic scale.'},
 particles:{prediction:'HIGH',focus:'heating-curve graph',stimulus:'A substance is heated at a steady rate. Its temperature rises, stays flat for several minutes, rises again, then stays flat a second time.',q:'What is happening during the two flat sections of the graph?',options:['The substance is changing state while temperature stays constant','The heater has stopped working twice','The substance is cooling down'],answer:0,why:'During melting and boiling, added energy changes state rather than raising temperature, producing a flat section.'},
 mixtures:{prediction:'HIGH',focus:'mixture vs compound diagrams',stimulus:'Diagram A shows two different-coloured single circles scattered together, unattached. Diagram B shows pairs of two different-coloured circles permanently joined, repeated throughout.',q:'Which diagram best represents a mixture rather than a compound?',options:['Diagram A','Diagram B','Both represent compounds'],answer:0,why:'A mixture contains substances physically combined; a compound shows atoms chemically bonded in fixed ratios, as in Diagram B.'},
 changes:{prediction:'MEDIUM',focus:'reaction-rate variable',stimulus:'Whole antacid tablets take 90 s to stop fizzing in water; crushed tablets of the same mass take 35 s at the same water temperature.',q:'What does this comparison best demonstrate?',options:['Smaller particle size increases reaction rate by increasing surface area','Crushing changes the tablet into a different substance','Water temperature caused the rate difference'],answer:0,why:'Crushing increases the surface area in contact with water, speeding the reaction without changing the substance or temperature.'},
 cells:{prediction:'MEDIUM',focus:'living vs non-living edge case',stimulus:'A virus cannot grow, respire or reproduce on its own, but can copy itself once inside a living host cell using the host’s machinery.',q:'Why do many scientists classify a virus as non-living outside a host?',options:['It cannot carry out key life processes independently','It is too small to be classified','It contains no genetic material at all'],answer:0,why:'Independent growth, respiration and reproduction are typically required for something to be classified as living.'},
 ecosystems:{prediction:'HIGH',focus:'random sampling method',stimulus:'To estimate a dandelion population in a large field, a student places a 1 m² quadrat at ten randomly chosen points, counts dandelions in each, then scales up the mean count to the field’s total area.',q:'Why are the quadrat locations chosen randomly rather than picked by the student?',options:['Random placement avoids bias towards patches that look more or less dense','Random placement guarantees an exact count with no error','It is only done to save time'],answer:0,why:'Random sampling reduces the chance that a subjective choice of location skews the population estimate.'},
 body:{prediction:'MEDIUM',focus:'recovery-curve graph',stimulus:'After exercise stops, a graph shows breathing rate falling steadily from 34 to 15 breaths/min over 6 minutes, then levelling off.',q:'What does the levelling-off point most likely represent?',options:['A return to a resting breathing rate','The point exercise restarted','A recording error'],answer:0,why:'A steady, unchanging value after a gradual fall typically represents the body returning to its resting state.'},
 forces:{prediction:'HIGH',focus:'projectile path from images',stimulus:'A strobe photograph shows a thrown ball at equal time intervals: the horizontal spacing between images stays constant, while the vertical spacing decreases then increases.',q:'What does the changing vertical spacing best show?',options:['Vertical velocity changes due to gravity while horizontal velocity stays constant','The ball speeds up horizontally','Gravity affects only horizontal motion'],answer:0,why:'Constant horizontal spacing shows constant horizontal velocity; changing vertical spacing shows gravity accelerating the ball vertically.'},
 circuits:{prediction:'MEDIUM',focus:'effect of current on the body',stimulus:'A safety chart shows currents below about 1 mA are barely noticeable, currents around 10–20 mA can make muscles contract and “freeze”, and currents above 100 mA can be life-threatening.',q:'Which conclusion is best supported by the chart?',options:['Increasing current through the body is associated with increasingly severe effects','Any detectable current is immediately life-threatening','Current has no relationship to the size of the effect'],answer:0,why:'The chart shows progressively more serious effects as current magnitude increases.'},
 energy:{prediction:'HIGH',focus:'potential–kinetic energy conversion',stimulus:'A pendulum bob is released from its highest point and swings through its lowest point to the same height on the other side, ignoring air resistance and friction.',q:'What happens to its energy at the lowest point of the swing, compared with the highest point?',options:['Gravitational potential energy has mostly converted to kinetic energy','All energy has been lost as heat','Potential energy has increased further'],answer:0,why:'As height decreases, stored gravitational potential energy converts to kinetic energy of motion, with total energy conserved.'},
 'maps-rockets':{prediction:'MEDIUM',focus:'scale measurement of a large phenomenon',stimulus:'A satellite image scale bar shows 2 cm represents 100 km. A cyclone’s visible cloud spiral measures 4.4 cm across on the image.',q:'What is the approximate real diameter of the cyclone?',options:['220 km','44 km','440 km'],answer:0,why:'4.4 ÷ 2 × 100 = 220 km, applying the image scale ratio.'},
 tectonics:{prediction:'MEDIUM',focus:'Earth’s internal structure',stimulus:'A cutaway diagram shows Earth with a thin outer layer, a thick middle layer of hot flowing rock, and a dense inner layer at the centre.',q:'Which layer does the thick, hot, flowing middle section represent?',options:['The mantle','The crust','The inner core'],answer:0,why:'The mantle is the thick layer of slowly flowing hot rock between the thin crust and the dense core.'},
 'structures-lab':{prediction:'MEDIUM',focus:'reading an unfamiliar dial',stimulus:'An unlabelled dial has a needle and a scale marked 0 to 200 in units of kPa, with a note that normal room air pressure reads about 101.',q:'What is this instrument most likely designed to measure?',options:['Pressure','Temperature','Electric current'],answer:0,why:'kPa (kilopascals) is a unit of pressure, and the described normal reading matches typical atmospheric pressure.'},
 'chem-environment':{prediction:'MEDIUM',focus:'predicting reaction evidence',stimulus:'An acid is added to a carbonate rock sample in a test tube. Bubbles form immediately and the tube feels warmer.',q:'Which products would this evidence best support?',options:['A gas has formed and the reaction released energy','Only a colour change occurred','No new substance has formed'],answer:0,why:'Gas bubbles and a temperature rise are evidence consistent with a reaction producing a gas and releasing energy.'},
 classification:{prediction:'HIGH',focus:'identifying a pest from data',stimulus:'A table lists three insect pests by antennae length, wing colour and typical crop damage. An unidentified insect has short antennae, clear wings and chews leaf edges, matching only one listed species exactly.',q:'What is the most valid way to identify the insect from this table?',options:['Compare its recorded features against each row until only one matches completely','Guess based on which pest is most common','Assume it is a new species'],answer:0,why:'Systematically matching every recorded feature to a table row is the valid method for identification from data.'},
 'bio-investigation':{prediction:'MEDIUM',focus:'scientific report sequence',stimulus:'A jumbled scientific report includes labelled sections: Results, Aim, Method, Conclusion and Hypothesis.',q:'Which is the most logical order for writing these sections?',options:['Aim, Hypothesis, Method, Results, Conclusion','Conclusion, Results, Method, Aim, Hypothesis','Method, Conclusion, Aim, Results, Hypothesis'],answer:0,why:'A report typically states its purpose and prediction before the method, then reports results before concluding.'},
 'light-sound':{prediction:'MEDIUM',focus:'speed of sound in different mediums',stimulus:'Sound recorded travelling through steel, water and air over the same distance arrives soonest through steel, then water, then air.',q:'What does this best show about the speed of sound?',options:['Sound generally travels fastest through solids and slowest through gases','Sound travels at the same speed in every material','Sound cannot travel through liquids'],answer:0,why:'Closer particle spacing in solids generally allows sound to travel faster than through liquids or gases.'},
 'motion-electricity':{prediction:'HIGH',focus:'area under a velocity–time graph',stimulus:'A velocity–time graph shows a constant velocity of 8 m/s for 5 s, forming a rectangle under the line.',q:'What does the area of this rectangle represent?',options:['The distance travelled during those 5 seconds','The acceleration during those 5 seconds','The final velocity only'],answer:0,why:'The area under a velocity–time graph equals distance travelled: 8 m/s × 5 s = 40 m.'},
 'water-cycle':{prediction:'MEDIUM',focus:'weather-station data table',stimulus:'A weather station records: 9 am — 14°C, 60% humidity, light wind; 3 pm — 24°C, 30% humidity, moderate wind.',q:'Which conclusion uses only this table’s data?',options:['Humidity was lower in the afternoon reading than the morning reading','It rained at 3 pm','Wind speed decreased throughout the day'],answer:0,why:'The table directly records 60% humidity at 9 am and 30% at 3 pm; rainfall and a decreasing wind trend are not recorded.'},
 reactions:{prediction:'MEDIUM',focus:'gas-product evidence',stimulus:'Vinegar (an acid) is added to baking soda (a carbonate). The mixture immediately fizzes and inflates a balloon placed over the container’s opening.',q:'What does the inflating balloon provide the strongest evidence for?',options:['A gas product was released by the reaction','The balloon dissolved','No chemical change took place'],answer:0,why:'A gas produced by the reaction is the most direct explanation for the balloon inflating.'},
 'body-systems':{prediction:'MEDIUM',focus:'effects of UV light',stimulus:'After long sun exposure without protection, human skin can burn and suffer long-term cell damage, while a shaded plastic garden chair nearby shows no such change.',q:'What does this comparison best suggest about ultraviolet (UV) light?',options:['UV light can damage living tissue, with the effect reduced by shade or protection','UV light affects only non-living materials','UV light has no effect without direct heat'],answer:0,why:'The skin damage from UV exposure shows it can harm living tissue, while shade reduces this effect.'},
 renewables:{prediction:'MEDIUM',focus:'reading a power meter',stimulus:'A plug-in power meter reads 12 W for a phone charger, 60 W for a desk lamp and 2000 W for a kettle while each operates.',q:'Based on these readings, which appliance uses electrical energy fastest while operating?',options:['The kettle','The desk lamp','The phone charger'],answer:0,why:'Power in watts measures the rate of energy use, and the kettle’s reading is far higher than the other appliances.'}
};
for(const [id,q] of Object.entries(latestPatterns)) questionBank[id].push(q);
